import fs from "fs";
import path from "path";

// 1. Setup paths
const THEME_JSON_PATH = path.resolve(__dirname, "./theme.json");
const OUTPUT_CSS_PATH = path.resolve(__dirname, "../tokens.css");

// Helper to convert #RRGGBB to R G B (required for Tailwind opacity support)
function hexToRgb(hex: string) {
  const cleanHex = hex.replace("#", "");
  const r = parseInt(cleanHex.substring(0, 2), 16);
  const g = parseInt(cleanHex.substring(2, 4), 16);
  const b = parseInt(cleanHex.substring(4, 6), 16);
  return `${r} ${g} ${b}`;
}

// 2. Read the Blueprint
console.log("🎨 Compiling Design Tokens...");
const themeData = JSON.parse(fs.readFileSync(THEME_JSON_PATH, "utf-8"));
const colors = themeData.colors;

// 3. Generate the CSS Variables string
let cssContent = `/* AUTO-GENERATED BY @craft/theme-core
  Do not edit this file directly. Update theme.json instead.
*/\n\n@layer base {\n  :root {\n`;

// Loop through the colors and inject them
for (const [semanticName, token] of Object.entries(colors)) {
  const colorToken = token as { base: string; foreground: string };
  
  // Create the base color variable (e.g., --primary)
  cssContent += `    --${semanticName}: ${hexToRgb(colorToken.base)};\n`;
  // Create the contrasting text color (e.g., --primary-foreground)
  cssContent += `    --${semanticName}-foreground: ${hexToRgb(colorToken.foreground)};\n`;
}

cssContent += `    --radius: ${themeData.radii?.button || "0.5rem"};\n`;
cssContent += `  }\n}\n`;

// 4. Write the file
fs.writeFileSync(OUTPUT_CSS_PATH, cssContent, "utf-8");
console.log(`✅ Design tokens successfully compiled to: ${OUTPUT_CSS_PATH}`);
